apiVersion: salaboy.com/v1alpha1
kind: Environment
metadata:
  name: team-a-dev-env
  namespace: staging
spec:
  compositionSelector:
    matchLabels:
      type: development
  parameters:
    installInfra: true