kind: Cluster
name: pipeline-manager
talos:
  version: v1.7.0
kubernetes:
  version: 1.30.0
features:
  enableWorkloadProxy: true
patches:
  - name: cni
    file: patches/cni.yaml
---
kind: ControlPlane
machineClass:
  name: pipeline-manager-controlplanes
  size: 3
patches:
  - name: cilium
    file: patches/cilium.yaml
  - name: argocd
    file: patches/argocd.yaml
  - name: monitoring
    file: patches/monitoring.yaml
  - name: workloads
    inline:
      cluster:
        allowSchedulingOnControlPlanes: true
---
kind: Workers
name: workers
machineClass:
  name: pipeline-manager-workers
  size: unlimited
